import type { Metadata, Viewport } from 'next';
import './globals.css';
import { MobileSidebarProvider } from '@/context/MobileSidebarContext';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { Roboto } from 'next/font/google';
import { FavoritesProvider } from '@/context/FavoritesContext';
import { CartProvider } from '@/context/CartContext';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Container from '@/components/Container';
import Canonical from '@/components/Canonical';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});

// Определяем метаданные без viewport
export const metadata: Metadata = {
  title: 'MobiStuff',
  description: 'Generated by create next app',
};

// Определяем viewport отдельно
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1, // Запрещает автоматический масштаб
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${roboto.variable} antialiased min-h-screen flex flex-col`}
      >
        <Canonical />
        <FavoritesProvider>
          <CartProvider>
            <MobileSidebarProvider>
              <Header />
              <div className="mt-[80px] flex-1">
                <Container>{children}</Container>
              </div>
              <Footer />
            </MobileSidebarProvider>
          </CartProvider>
        </FavoritesProvider>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
