import type { Metadata } from 'next';
import './globals.css';

import { Roboto } from 'next/font/google';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Container from '@/components/Container';
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // выбери нужные веса
  variable: '--font-roboto', // можно переопределить имя переменной
});

export const metadata: Metadata = {
  title: 'MobiStuff',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk ">
      <body className={`${roboto.variable}  antialiased min-h-screen`}>
        <Header />

        <main className="w-full border-none  ">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
