export const defaultPromotions = [
  {
    title: 'Знижки до -30%',
    subtitle: 'На зарядні пристрої',
    cta: 'До покупок',
    color: '#3D4F5C',
    emoji: '🔌',
    linkType: 'on_sale' as const,
    categorySlug: 'category-zaryadki-i-kabeli',
    categoryTitle: 'Зарядки та кабелі',
    sortOrder: 0,
    isActive: true,
  },
  {
    title: 'Новинки',
    subtitle: 'Чохли для iPhone',
    cta: 'Дивитись',
    color: '#45435F',
    emoji: '📱',
    linkType: 'category' as const,
    categorySlug: 'category-chehli',
    categoryTitle: 'Чохли',
    subcategorySlug: 'category-apple',
    subcategoryTitle: 'Apple',
    sortOrder: 1,
    isActive: true,
  },
  {
    title: 'Акція тижня',
    subtitle: 'Навушники зі знижкою',
    cta: 'До покупок',
    color: '#3A4A62',
    emoji: '🎧',
    linkType: 'on_sale' as const,
    categorySlug: 'category-naushniki',
    categoryTitle: 'Навушники',
    sortOrder: 2,
    isActive: true,
  },
];
